<?php
$arr = [
	"Pay Now",
	"Useful Links",
	"Change Password",
	"Enter your current password",
	"Enter new password",
	"Repeat password",
	"Confirm Password",
	"Forgot Your Password",
	"Recover Password",
	"Email address",
	"Send Link",
	"Reset Password",
	"New Password",
	"Confirm New Password",
	"2 Step Verification",
	"2 FA Code",
	"Submit",
	"Email Verification",
	"Code",
	"Resend code",
	"SMS Verification",
	"Login",
	"Username or Email",
	"Password",
	"Forgot password",
	"Log In",
	"Google",
	"Facebook",
	"Github",
	"Don't have an account",
	"Create an account",
	"Sign Up",
	"Full Name",
	"Email",
	"User Name",
	"Username",
	"signup",
	"Already have an account",
	"Login here",
	"403 Forbidden",
	"Forbidden",
	"You don't have permission to access ‘/’ on this server",
	"Page not found",
	"Back to Homepage",
	"Method Not Allowed",
	"405",
	"419",
	"Sorry, your session",
	"500",
	"Internal Server Error",
	"The server encountered an internal error misconfiguration and was unable to complate your request.Please contact the server administrator.",
	"Loading",
	"Home",
	"All Rights Reserved",
	"Dashboard",
	"Pay Bill",
	"Pay List",
	"Bill Pay Request",
	"Transaction",
	"Support Ticket",
	"Search",
	"Enter search keyword",
	"Result",
	"Account Settings",
	"2 FA Security",
	"Sign Out",
	"Quick Links",
	"About",
	"FAQ",
	"Blog",
	"Contact",
	"Company Policy",
	"Contact Us",
	"Copyright",
	"home",
	"features",
	"blog",
	"Clear all",
	"You have no notifications",
	"Read more",
	"How it works",
	"Enter your mail",
	"Subscribe",
	"KYC Form",
	"KYC Information",
	"Your kyc verification process in pending.",
	"Your kyc is verified",
	"Your previous kyc is rejected",
	"Verify your process instantly.",
	"Allowed JPG, jpeg or PNG. Max size of 2048K",
	"submit",
	"Notification",
	"Notification Templates",
	"We need permission from your browser to show notifications.",
	"Request Permission",
	"Type",
	"Sms",
	"Push",
	"In App",
	"Save Changes",
	"Bill Details",
	"Back",
	"Bill method",
	"Payment Gateway",
	"Transaction Id",
	"Status",
	"Pending",
	"Completed",
	"Return",
	"Exchange Rate",
	"Pay In Base",
	"Bill Information",
	"Category",
	"Country Code",
	"Amount",
	"Charge",
	"Payable Amount",
	"Country",
	"Select Country",
	"Services",
	"Enter Amount",
	"continue",
	"Bill Pay List",
	"SL",
	"Date & Time",
	"Action",
	"Filter",
	"Select Service",
	"Success",
	"Date",
	"Preview Payment",
	"Select payment method",
	"Wallet",
	"Service",
	"Min - Max Amount",
	"ateway Charge",
	"pay",
	"Trx Number",
	"Method",
	"Payable",
	"Approved",
	"Rejected",
	"Admin Feedback",
	"Close",
	"Your Card Information",
	"Enter your card number",
	"Enter the name on your card",
	"Payment Preview",
	"PLEASE SEND EXACTLY",
	"SCAN TO SEND",
	"TO",
	"CARD NAME",
	"CARD NUMBER",
	"EXPIRATION DATE",
	"CVC CODE",
	"Please Pay",
	"Pay with Khalti",
	"Please follow the instruction below",
	"You have requested to deposit",
	"Upload New Photo",
	"Confirm Now",
	"Pay with VoguePay",
	"profile",
	"Identity Verification",
	"Profile Details",
	"reset",
	"Allowed JPG or PNG. Max size of 3000k",
	"Name",
	"Your full name",
	"City",
	"Enter your city",
	"Email Address",
	"Phone",
	"language",
	"Address",
	"save changes",
	"New Ticket",
	"Subject",
	"Message",
	"Submit Ticket",
	"Tickets Log",
	"Last Reply",
	"Open",
	"Answered",
	"Replied",
	"Closed",
	"Customer Replied",
	"Confirmation !",
	"Are you want to close ticket",
	"Confirm",
	"Transaction List",
	"Transaction ID",
	"Remark",
	"Created Time",
	"Transaction Filter",
	"Min Amount",
	"Max Amount",
	"Transaction Date",
	"Fund",
	"All Type",
	"No records has been added yet.",
	"2 Step Security",
	"Two Factor Authenticator",
	"Copy",
	"Disable Two Factor Authenticator",
	"Enable Two Factor Authenticator",
	"Google Authenticator",
	"Use Google Authenticator to Scan the QR code  or use the code",
	"Google Authenticator is a multifactor app for mobile devices. It generates timed codes used during the 2-step verification process. To use Google Authenticator, ▶",
	"Download App",
	"Verify Your OTP",
	"Enter Google Authenticator Code",
	"Verify",
	"Verify Your OTP to Disable",
	"Do not miss any single important notification! Allow your browser to get instant push notification",
	"Allow me",
	"Please allow your browser to get instant push notification. Allow it from notification setting.",
	"Wallet Balance",
	"last 30 days",
	"Pending Bill",
	"Return Bill",
	"Transaction Summary",
	"Bill Statistics",
	"About Us",
	"Blog Details",
	"Phone:",
	"Email:",
	"Address:",
	"Drop Us a Line",
	"Your Name",
	"E-mail Address",
	"Your Subject",
	"Your Massage",
	"Send a massage",
	"Feature",
	"Sorry",
	"We really appreciate you giving us a moment of your time today but unfortunately the payment was unsuccessful due to",
	"it seems some issue in server to server communication. Kindly connect with administrator",
	"Go Back to Home",
	"THANK YOU",
	"Thanks a bunch for filling that out. It means a lot to us, just like you do! We really appreciate you giving us a moment of your time today. Thanks for being with us.",
];
return $arr;
